package com.feicui.domain;
// Generated 2018-5-31 15:28:53 by Hibernate Tools 4.3.5.Final

import java.util.Date;

/**
 * Homework generated by hbm2java
 */
public class Homework implements java.io.Serializable {

	private Integer homeworkid;
	private User user;
	private String info;
	private Date cdate;

	public Homework() {
	}

	public Homework(User user, String info, Date cdate) {
		this.user = user;
		this.info = info;
		this.cdate = cdate;
	}

	public Integer getHomeworkid() {
		return this.homeworkid;
	}

	public void setHomeworkid(Integer homeworkid) {
		this.homeworkid = homeworkid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Date getCdate() {
		return this.cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

}
