package com.feicui.domain;
// Generated 2018-5-31 15:28:53 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Score generated by hbm2java
 */
public class Score implements java.io.Serializable {

	private Integer scoreid;
	private Course course;
	private User user;
	private BigDecimal score;
	private Date examdate;
	private String eaxmtype;

	public Score() {
	}

	public Score(Course course, User user, BigDecimal score, Date examdate, String eaxmtype) {
		this.course = course;
		this.user = user;
		this.score = score;
		this.examdate = examdate;
		this.eaxmtype = eaxmtype;
	}

	public Integer getScoreid() {
		return this.scoreid;
	}

	public void setScoreid(Integer scoreid) {
		this.scoreid = scoreid;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public BigDecimal getScore() {
		return this.score;
	}

	public void setScore(BigDecimal score) {
		this.score = score;
	}

	public Date getExamdate() {
		return this.examdate;
	}

	public void setExamdate(Date examdate) {
		this.examdate = examdate;
	}

	public String getEaxmtype() {
		return this.eaxmtype;
	}

	public void setEaxmtype(String eaxmtype) {
		this.eaxmtype = eaxmtype;
	}

}
