package com.feicui.domain;
// Generated 2018-5-31 15:28:53 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Teachmode generated by hbm2java
 */
public class Teachmode implements java.io.Serializable {

	private Integer teachmodeid;
	private String tname;
	private String info;
	private Set users = new HashSet(0);

	public Teachmode() {
	}

	public Teachmode(String tname, String info, Set users) {
		this.tname = tname;
		this.info = info;
		this.users = users;
	}

	public Integer getTeachmodeid() {
		return this.teachmodeid;
	}

	public void setTeachmodeid(Integer teachmodeid) {
		this.teachmodeid = teachmodeid;
	}

	public String getTname() {
		return this.tname;
	}

	public void setTname(String tname) {
		this.tname = tname;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
