package com.feicui.domain;
// Generated 2018-5-31 15:28:53 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer uid;
	private Room room;
	private Teachmode teachmode;
	private Trusteetype trusteetype;
	private String username;
	private String password;
	private String realname;
	private String gender;
	private Date birthday;
	private String cellphone;
	private String address;
	private String email;
	private BigDecimal price;
	private BigDecimal sal;
	private Set roles = new HashSet(0);
	private Set homeworks = new HashSet(0);
	private Set scores = new HashSet(0);

	public User() {
	}

	public User(Room room, Teachmode teachmode, Trusteetype trusteetype, String username, String password,
			String realname, String gender, Date birthday, String cellphone, String address, String email,
			BigDecimal price, BigDecimal sal, Set roles, Set homeworks, Set scores) {
		this.room = room;
		this.teachmode = teachmode;
		this.trusteetype = trusteetype;
		this.username = username;
		this.password = password;
		this.realname = realname;
		this.gender = gender;
		this.birthday = birthday;
		this.cellphone = cellphone;
		this.address = address;
		this.email = email;
		this.price = price;
		this.sal = sal;
		this.roles = roles;
		this.homeworks = homeworks;
		this.scores = scores;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	public Teachmode getTeachmode() {
		return this.teachmode;
	}

	public void setTeachmode(Teachmode teachmode) {
		this.teachmode = teachmode;
	}

	public Trusteetype getTrusteetype() {
		return this.trusteetype;
	}

	public void setTrusteetype(Trusteetype trusteetype) {
		this.trusteetype = trusteetype;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getCellphone() {
		return this.cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getSal() {
		return this.sal;
	}

	public void setSal(BigDecimal sal) {
		this.sal = sal;
	}

	public Set getRoles() {
		return this.roles;
	}

	public void setRoles(Set roles) {
		this.roles = roles;
	}

	public Set getHomeworks() {
		return this.homeworks;
	}

	public void setHomeworks(Set homeworks) {
		this.homeworks = homeworks;
	}

	public Set getScores() {
		return this.scores;
	}

	public void setScores(Set scores) {
		this.scores = scores;
	}

}
